# Generated by Django 6.0.4 on 2026-05-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='model',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
