# Generated by Django 6.0.4 on 2026-05-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_updated_at_model_updated_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='CarModel',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={},
        ),
    ]
