# Generated by Django 6.0.4 on 2026-05-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name']},
        ),
    ]
